version: "3"

services:
  db:
    container_name: geoshpae-db
    image: geoshape-db
    ports:
      - "8090:8090"
    networks:
      - geoshape
    restart: unless-stopped
    volumes:
      - ./data/pb_data:/pb_data
  web:
    container_name: geoshape-web
    image: geoshape-web
    depends_on:
      db:
        condition: service_started
    environment:
      PUBLIC_POCKETBASE_URL: https://geoshape.danielmuenstermann.de/api
    ports:
      - "3000:3000"
    networks:
      - geoshape
    restart: unless-stopped

networks:
  geoshape:
    driver: bridge
